<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE listado [
    <!ELEMENT listado (participante*)>
    <!ELEMENT participante ((nombre,apellidos)|(apellidos,nombre))>
    <!ELEMENT nombre ANY>
    <!ELEMENT apellidos ANY>

]>
    <listado>
        <participante>
            <nombre>Ana María</nombre>
            <apellidos>Pérez Casado</apellidos>
    </participante>
    <participante>
        <apellidos>López Rico</apellidos>
        <nombre>Nuria</nombre>
    </participante>
</listado>