=== olmedix/Lenguaje_Marcas/Tema2/ejemplos-element/coche.dtd
<!ELEMENT coche (marca,modelo,ocasion?, combustible , extra*)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT ocasion EMPTY>
<!ELEMENT combustible (gasolina|diesel|electrico)>
<!ELEMENT gasolina EMPTY>
<!ELEMENT diesel EMPTY>
<!ELEMENT electrico EMPTY>
<!ELEMENT extra (#PCDATA)>

=== olmedix/Lenguaje_Marcas/Tema2/ejemplos-element/coche.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE coche SYSTEM "coche.dtd">

<coche>
	<marca>Renault</marca>
	<modelo>Clio</modelo>
	<ocasion/>
	<combustible>
		<gasolina/>
	</combustible>
	<extra>elevalunas el√©ctrico</extra>
	<extra>asientos calefactables</extra>
</coche>
