=== olmedix/Lenguaje_Marcas/Tema2/estudioExamen/ejer05.dtd
<!ELEMENT liga_futbol (partido*)>
<!ELEMENT partido (equipo_local,equipo_visitante)>
<!ELEMENT equipo_local (#PCDATA)>
<!ATTLIST equipo_local goles NMTOKEN #REQUIRED>

<!ELEMENT equipo_visitante (#PCDATA)>
<!ATTLIST equipo_visitante goles NMTOKEN #REQUIRED>

=== olmedix/Lenguaje_Marcas/Tema2/estudioExamen/ejer05.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE liga_futbol SYSTEM "ejer05.dtd">

<liga_futbol>
    <partido>
        <equipo_local goles="3">madrid</equipo_local>
        <equipo_visitante goles="2">barsa</equipo_visitante>
    </partido>
    <partido>
        <equipo_local goles="3">voka juniors</equipo_local>
        <equipo_visitante goles="2">sparta</equipo_visitante>
    </partido>
    <partido>
        <equipo_local goles="3">munich</equipo_local>
        <equipo_visitante goles="2">granada</equipo_visitante>
    </partido>


</liga_futbol>
